### PR TITLE
hi

### PR DESCRIPTION
**Pull request by Lakshmi19496**
hlo

### CODE REVIEW

**Comment by sumareddy44** [comment]
it is not optimized pls review

**Comment by Lakshmi19496** [comment]
see nicely

**Comment by sumareddy44** [comment]
write it nicely

**Comment by Lakshmi19496** [comment]
read it nicely

**Comment by sumareddy44** [comment]
optimize nicely

**Comment by Lakshmi19496** [comment]
ok

**Review by sumareddy44 — APPROVED** [review]

**Review by sumareddy44 — APPROVED** [review]

**Review by sumareddy44 — APPROVED** [review]

**Pull request closed without merging**
